#!/bin/bash

if ! is-executable code ; then
	echo "code is not installed, install code then try again"
	exit 0
fi

if [ -z DOTFILES_DIR ]; then
	echo "DOTFILES_DIR variable not set, aborting"
	exit 0
fi

SRC="$DOTFILES_DIR/vscode/User"
if [ -d SRC ]; then
	echo "missing vscode ${SRC} folder, aborting"
	exit 0
fi

if [ is-macos ]; then
	DESTINATION="$HOME/Library/Application Support/Code/User"
else
	DESTINATION="$HOME/.config/Code/User"
fi

echo "copying vscode settings to ${DESTINATION}"

if ! [ -L "${DESTINATION}" ]; then
	echo "Symlink already exists"
else
	echo "deleting ${DESTINATION}"
	rm -rf "${DESTINATION}" && echo "Deleted"

	echo "Linking ${SRC} to ${DESTINATION}"
	ln -s "${SRC}" "${DESTINATION}" && echo "Linked!"
fi

EXTENSION_FOLDER="${HOME}/.vscode"

if [ -d "${EXTENSION_FOLDER}" ]; then
	rm -rf "${EXTENSION_FOLDER}" && echo "Deleted ${EXTENSION_FOLDER}"
fi

extensions=(
	ms-vscode.go # golang
	ms-vscode.sublime-keybindings # sublime keybindings
	dbaeumer.vscode-eslint # eslint
	pkief.material-icon-theme # icons
	esbenp.prettier-vscode # prettier
	ryannaddy.laravel-artisan # laravel artisan
	felixfbecker.php-debug # php debug
	neilbrayfield.php-docblocker # php docblocker
	bmewburn.vscode-intelephense-client # php intellisense
	kokororin.vscode-phpfmt # php formatting
	tobiasalthoff.atom-material-theme # theme
	eg2.vscode-npm-script # npm
	christian-kohler.npm-intellisense # npm intellisense
	blanu.vscode-styled-jsx # vscode styled jsx
	coenraads.bracket-pair-colorizer # bracket colors
)

extension_install() {
	local extension=$1
	echo "installing ${extension}"
	code --install-extension $extension
}

for EXTENSION in ${extensions[@]}; do
	extension_install $EXTENSION
done


echo "done installing vscode setup!"
