#!/usr/bin/env bash

mkdir -p $HOME/applications

git clone https://github.com/neovim/neovim.git $HOME/applications/neovim

cd $HOME/applications/neovim
git fetch
git checkout release-0.10

sudo apt update && sudo apt install cmake gettext lua5.1 liblua5.1-0-dev

make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
