#!/usr/bin/env bash

ws() {
    local selected=$(git worktree list | grep -v '(bare)' | awk '{print $1}' | fzf --prompt="Select worktree: ")
    
    if [[ -n "$selected" ]]; then
        echo "Changing to: $selected"
        cd "$selected"
    else
        echo "No worktree selected"
    fi
}
