#!/usr/bin/env bash

# check if we are in a git repo
if ! { [ -d .git ] || git rev-parse --git-dir > /dev/null 2>&1; }; then
  echo "not in a repo, exiting"
  exit 1
fi

current=$(pwd)
# root worktree folder
current_dir=$(git -C "$current" worktree list | head -n 1 | awk '{print $1}')
main_worktree=$(git -C "$current_dir" --work-tree "$current_dir" rev-parse --show-toplevel)

# worktrees=$(git -C "$current_dir" --work-tree "$current_dir" worktree list)
tmux_running=$(pgrep tmux)
# worktree_paths=$(git -C "$current_dir" --work-tree "$current_dir" worktree list | awk '{print $1}')
selected=$(git -C "$current_dir" --work-tree "$current_dir" worktree list | awk '{print $2 " -> " $1}' | fzf | awk '{print $3}')


worktree_root_name=$(basename "$main_worktree")
worktree_name=$(basename "$selected")
# branch=$(git -C "$selected" --work-tree "$selected" rev-parse --abbrev-ref HEAD)
session_name="$worktree_root_name>$worktree_name"

tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    echo "new-session -s $session_name on path $selected"
    exit 0
fi

if ! tmux has-session -t="$session_name" 2> /dev/null; then
    tmux new-session -ds "$session_name" -c "$selected"
fi

tmux switch-client -t "$session_name"
